const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('lanRemote', {
  getAppInfo: () => ipcRenderer.invoke('app-info'),
  getDevices: () => ipcRenderer.invoke('devices-list'),
  refreshDevices: () => ipcRenderer.invoke('refresh-devices'),
  getNativeV2Status: () => ipcRenderer.invoke('native-v2-status'),
  getGameStreamStatus: () => ipcRenderer.invoke('game-stream-status'),
  getGameStreamInstallStatus: () => ipcRenderer.invoke('game-stream-install-status'),
  installGameStreamTool: (options) => ipcRenderer.invoke('game-stream-install-tool', options),
  startGameStreamHost: (options) => ipcRenderer.invoke('game-stream-start-host', options),
  stopGameStreamHost: () => ipcRenderer.invoke('game-stream-stop-host'),
  startGameStreamClient: (options) => ipcRenderer.invoke('game-stream-start-client', options),
  stopGameStreamClient: () => ipcRenderer.invoke('game-stream-stop-client'),
  pairGameStreamClient: (options) => ipcRenderer.invoke('game-stream-pair-client', options),
  submitGameStreamPairPin: (options) => ipcRenderer.invoke('game-stream-submit-pair-pin', options),
  requestGameStreamRemoteHost: (device, options) => ipcRenderer.invoke('game-stream-request-remote-host', { device, options }),
  openGameStreamSunshine: (host) => ipcRenderer.invoke('game-stream-open-sunshine', host),
  openGameStreamDownload: (target) => ipcRenderer.invoke('game-stream-open-download', target),
  startNativeV2Client: (options) => ipcRenderer.invoke('native-v2-start-client', options),
  stopNativeV2Client: () => ipcRenderer.invoke('native-v2-stop-client'),
  startNativeV2Host: (options) => ipcRenderer.invoke('native-v2-start-host', options),
  requestNativeV2RemoteHost: (device, options) => ipcRenderer.invoke('native-v2-request-remote-host', { device, options }),
  getNativeV2RouteLocalAddress: (targetIp) => ipcRenderer.invoke('native-v2-route-local-address', targetIp),
  stopNativeV2Host: () => ipcRenderer.invoke('native-v2-stop-host'),
  saveDevicePreview: (id, dataUrl) => ipcRenderer.invoke('save-device-preview', id, dataUrl),
  setWindowFullscreen: (fullScreen) => ipcRenderer.invoke('set-window-fullscreen', fullScreen),
  windowAction: (action) => ipcRenderer.invoke('window-action', action),
  getMacPermissionStatus: () => ipcRenderer.invoke('mac-permission-status'),
  getScreenCaptureStatus: () => ipcRenderer.invoke('screen-capture-status'),
  openScreenCaptureSettings: () => ipcRenderer.invoke('open-screen-capture-settings'),
  resetScreenCapturePermission: () => ipcRenderer.invoke('reset-screen-capture-permission'),
  requestAccessibilityPermission: () => ipcRenderer.invoke('request-accessibility-permission'),
  openAccessibilitySettings: () => ipcRenderer.invoke('open-accessibility-settings'),
  resetAccessibilityPermission: () => ipcRenderer.invoke('reset-accessibility-permission'),
  onDevicesUpdated: (callback) => ipcRenderer.on('devices-updated', (_event, payload) => callback(payload)),
  onHostLog: (callback) => ipcRenderer.on('host-log', (_event, payload) => callback(payload)),
  onNativeV2Status: (callback) => ipcRenderer.on('native-v2-status', (_event, payload) => callback(payload)),
  onGameStreamStatus: (callback) => ipcRenderer.on('game-stream-status', (_event, payload) => callback(payload)),
  onGameStreamInstallProgress: (callback) => ipcRenderer.on('game-stream-install-progress', (_event, payload) => callback(payload)),
});
